# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_regex"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2022, John S. Urban"
description = "Fortran interface to the POSIX 1003.2 regular expression library"
categories = ["Regular Expressions"]
keywords = ["fortran", "regular expression", "POSIX 1003.2", ""]
homepage = "https://github.com/urbanjost/M_regex.git"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = false
#library = true

#[[executable]]
#   name="unique"
#   source-dir="app"
#   main="unique.f90"
#   [executable.dependencies]
#   M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }

[[test]]
name="test_suite_M_regex"
source-dir="test"
main="test_suite_M_regex.f90"
[test.dependencies]
M_framework = { git = "https://github.com/urbanjost/M_framework.git" }
#M_framework = {namespace = "GPF"}
